Repository Patrowl/PatrowlEngines, pull requests merged in 2020-05, with the labels that each got.

#73 Eyewitness upgrade: parametrize CEIL & add is_forsale function
  .gitignore
  engines/eyewitness/engine-eyewitness.py
  engines/eyewitness/eyewitness.json.sample
Labels: enhancement

#65 Fixes & Improvements for OpenVAS
  engines/nmap/engine-nmap.py
  engines/openvas/engine-openvas.py
Labels: bug, enhancement

#81 Fix Error in nmap scans #59
  engines/nmap/engine-nmap.py
  engines/nmap/requirements.txt
Labels: bug
