Repository Patrowl/PatrowlEngines, pull requests merged in 2020-11, with the labels that each got.

#116 Fix apivoid
  engines/apivoid/Dockerfile
  engines/apivoid/README.md
  engines/apivoid/__init__.py
  engines/apivoid/apivoid.json.sample
  engines/apivoid/tests/test_apivoid.py
  engines/eyewitness/Dockerfile
  engines/eyewitness/__init__.py
  engines/eyewitness/eyewitness.json.sample
Labels: bug

#111 Add vuln search to droopescan
  engines/droopescan/Dockerfile
  engines/droopescan/README.md
  engines/droopescan/__init__.py
  engines/droopescan/droopescan.json
  engines/droopescan/droopescan.json.sample
  engines/droopescan/engine-droopescan.py
  engines/droopescan/tests/api_droopescan.py
  engines/droopescan/tests/test_droopescan.py
Labels: enhancement

#113 Fix RCE
  engines/nmap/engine-nmap.py
Labels: security

#121 Reworked the pastebin_monitor engine
  engines/pastebin_monitor/LICENSE
  engines/pastebin_monitor/engine-pastebin_crawler.py
  engines/pastebin_monitor/engine-pastebin_monitor.py
  engines/pastebin_monitor/pastebin_monitor.json.sample
  engines/pastebin_monitor/requirements.txt
Labels: enhancement
