Repository Patrowl/PatrowlEngines, pull requests merged in 2023-01, with the labels that each got.

#241 [Snyk] Security upgrade setuptools from 39.0.1 to 65.5.1
  engines/arachni/requirements.txt
Labels: security

#242 [Snyk] Security upgrade setuptools from 39.0.1 to 65.5.1
  engines/virustotal/requirements.txt
Labels: security

#243 [Snyk] Security upgrade setuptools from 39.0.1 to 65.5.1
  engines/nessus/requirements.txt
Labels: security

#245 [Snyk] Security upgrade setuptools from 39.0.1 to 65.5.1
  engines/owl_code/requirements.txt
Labels: security

#246 [Snyk] Security upgrade setuptools from 39.0.1 to 65.5.1
  engines/owl_leaks/requirements.txt
Labels: security

#248 [Snyk] Security upgrade setuptools from 39.0.1 to 65.5.1
  engines/cortex/requirements.txt
Labels: security

#249 [Snyk] Security upgrade setuptools from 39.0.1 to 65.5.1
  engines/urlvoid/requirements.txt
Labels: security

#236 1.5.9
  VERSION
  engines/apivoid/Dockerfile
  engines/apivoid/VERSION
  engines/apivoid/requirements.txt
  engines/arachni/requirements.txt
  engines/censys/Dockerfile.old
  engines/censys/VERSION
  engines/censys/requirements.txt
  engines/certstream/Dockerfile
  engines/certstream/VERSION
  engines/cortex/Dockerfile
  engines/cortex/VERSION
  engines/cortex/requirements.txt
  engines/cybelangel/Dockerfile
  engines/cybelangel/VERSION
  engines/droopescan/Dockerfile
  engines/droopescan/VERSION
  engines/eyewitness/requirements.txt
  engines/nessus/Dockerfile
  engines/nessus/VERSION
  engines/nessus/requirements.txt
  engines/nmap/Dockerfile
  engines/nmap/VERSION
  engines/nmap/requirements.txt
  engines/openvas/Dockerfile
  engines/openvas/VERSION
  engines/owl_code/Dockerfile
  engines/owl_code/VERSION
  engines/owl_code/requirements.txt
  engines/owl_dns/Dockerfile
  engines/owl_dns/VERSION
  engines/owl_dns/engine-owl_dns.py
  engines/owl_dns/owl_dns.json.sample
  engines/owl_dns/requirements.txt
  engines/owl_leaks/Dockerfile
  engines/owl_leaks/VERSION
  engines/owl_leaks/requirements.txt
  engines/owl_request/Dockerfile
  engines/owl_request/VERSION
  engines/pastebin_monitor/Dockerfile
  engines/pastebin_monitor/VERSION
  engines/shhgit/Dockerfile
  engines/shhgit/VERSION
  engines/ssllabs/Dockerfile
  engines/ssllabs/VERSION
  engines/ssllabs/requirements.txt
  engines/sslscan/Dockerfile
  engines/sslscan/VERSION
  engines/urlvoid/Dockerfile
  engines/urlvoid/VERSION
  engines/urlvoid/requirements.txt
  engines/virustotal/Dockerfile
  engines/virustotal/VERSION
  engines/virustotal/requirements.txt
  engines/wpscan/Dockerfile
  engines/wpscan/VERSION
  engines/wpscan/__init__.py
  engines/wpscan/engine-wpscan.py
  engines/wpscan/wpscan.json.sample
  skeleton/requirements.txt
Labels: enhancement, dependencies, fix

#266 1.5.9-1 hotfix dependencies
  engines/nmap/requirements.txt
  engines/owl_dns/Dockerfile
  engines/owl_dns/Dockerfile.alpine
Labels: dependencies, fix

#267 1.5.9-2 hotfix II
  VERSION
  engines/apivoid/Dockerfile
  engines/apivoid/VERSION
  engines/apivoid/requirements.txt
  engines/nmap/Dockerfile
  engines/nmap/VERSION
  engines/nmap/requirements.txt
  engines/owl_dns/Dockerfile
  engines/owl_dns/Dockerfile.alpine
  engines/owl_dns/VERSION
  engines/owl_dns/requirements.txt
Labels: dependencies, fix
