Repository Patrowl/PatrowlEngines, pull requests merged in 2023-03, with the labels that each got.

#253 [Snyk] Security upgrade certifi from 2022.9.24 to 2022.12.7
  engines/ssllabs/requirements.txt
Labels: dependencies, security

#263 [Snyk] Security upgrade certifi from 2022.9.24 to 2022.12.7
  engines/owl_dns/requirements.txt
Labels: dependencies, security

#260 [Snyk] Security upgrade urllib3 from 1.25 to 1.26.5
  engines/arachni/requirements.txt
Labels: dependencies, security

#271 Multiple CPE on service with CPE #270
  engines/nmap/engine-nmap.py
Labels: enhancement

#280 Fix #279 owl_dns: support 'email' as asset datatype
  engines/nmap/banner.py
  engines/owl_dns/engine-owl_dns.py
Labels: enhancement, fix

#275 create finding for each spf dns entry
  engines/owl_dns/engine-owl_dns.py
Labels: enhancement

#277 Nmap opti
  engines/nmap/Dockerfile
  engines/nmap/VERSION
  engines/nmap/engine-nmap.py
  engines/owl_dns/Dockerfile.alpine
Labels: enhancement

#297 MCS Spring '23
  engines/apivoid/requirements.txt
  engines/arachni/requirements.txt
  engines/censys/requirements.txt
  engines/nmap/requirements.txt
  engines/owl_dns/requirements.txt
  engines/ssllabs/requirements.txt
  engines/sslscan/requirements.txt
Labels: dependencies, security
